# Generated by Django 4.2.7 on 2025-12-11 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='access_log/%Y/%m/%d')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='감지 시간')),
                ('log_type', models.CharField(choices=[('VISITOR', '방문자'), ('PACKAGE', '택배')], help_text='VISITOR: 방문자, PACKAGE: 택배', max_length=10, verbose_name='로그 타입')),
                ('description', models.TextField(help_text='YOLO가 감지한 원본 객체명 (예: person, suitcase, backpack)', verbose_name='설명')),
            ],
            options={
                'verbose_name': '접근 로그',
                'verbose_name_plural': '접근 로그',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
